# Generated by Django 6.0.4 on 2026-05-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_no', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('atc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('processor_type', models.CharField(default='intel', max_length=20)),
                ('processor', models.CharField(max_length=255)),
                ('pro_descp', models.TextField(blank=True, null=True)),
                ('processor_price', models.FloatField(default=0)),
                ('ram', models.CharField(max_length=100)),
                ('ram_price', models.FloatField(default=0)),
                ('hdd', models.CharField(blank=True, max_length=100, null=True)),
                ('hdd_price', models.FloatField(default=0)),
                ('ssd1', models.CharField(blank=True, max_length=100, null=True)),
                ('ssd1_price', models.FloatField(default=0)),
                ('ssd2', models.CharField(blank=True, max_length=100, null=True)),
                ('ssd2_price', models.FloatField(default=0)),
                ('software1', models.TextField()),
                ('gp', models.TextField()),
                ('os', models.CharField(max_length=100)),
                ('os_price', models.FloatField(default=0)),
                ('dvd', models.CharField(blank=True, max_length=50, null=True)),
                ('dvd_price', models.FloatField(default=0)),
                ('wifi', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_price', models.FloatField(default=0)),
                ('monitor', models.CharField(max_length=100)),
                ('monitor_price', models.FloatField(default=0)),
                ('cabinet', models.CharField(max_length=50)),
                ('cabinet_price', models.FloatField(default=0)),
                ('keyboard', models.CharField(blank=True, max_length=100, null=True)),
                ('keyboard_price', models.FloatField(default=0)),
                ('warranty', models.CharField(max_length=50)),
                ('warranty_price', models.FloatField(default=0)),
                ('motherboard_type', models.CharField(default='intel', max_length=20)),
                ('motherboard', models.CharField(max_length=255)),
                ('motherboard_descp', models.TextField(blank=True, null=True)),
                ('motherboard_price', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('epbg', models.FloatField(default=0)),
                ('freightInstallation', models.CharField(default='Yes', max_length=50)),
                ('freightInstallation_price', models.FloatField(default=1000)),
                ('hddreturnable', models.CharField(default='Yes', max_length=50)),
                ('hddreturnable_price', models.FloatField(default=0)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('analyser_note', models.TextField(blank=True, null=True)),
                ('analyser_username', models.CharField(blank=True, max_length=100, null=True)),
                ('review_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyser', 'Analyzer'), ('user', 'User')], default='user', max_length=20)),
            ],
        ),
    ]
