# Generated by Django 6.0.4 on 2026-05-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIOProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('bid_no', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('pro_price', models.FloatField(default=0)),
                ('ram_price', models.FloatField(default=0)),
                ('hdd_price', models.FloatField(default=0)),
                ('ssd_price', models.FloatField(default=0)),
                ('dealer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BidProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_no', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('bid_qualify', models.CharField(blank=True, max_length=50, null=True)),
                ('bid_disqualify_reason', models.TextField(blank=True, null=True)),
                ('dealer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=100)),
                ('pro_price', models.IntegerField()),
                ('ram', models.CharField(max_length=50)),
                ('ram_price', models.IntegerField()),
                ('hdd', models.CharField(blank=True, max_length=50, null=True)),
                ('hdd_price', models.IntegerField(blank=True, null=True)),
                ('ssd', models.CharField(blank=True, max_length=50, null=True)),
                ('ssd_price', models.IntegerField(blank=True, null=True)),
                ('gp', models.CharField(blank=True, max_length=50, null=True)),
                ('gp_price', models.IntegerField(blank=True, null=True)),
                ('os', models.CharField(max_length=100)),
                ('os_price', models.IntegerField()),
                ('motherboard', models.CharField(max_length=100)),
                ('motherboard_price', models.IntegerField()),
                ('dvd', models.CharField(blank=True, max_length=20, null=True)),
                ('dvd_price', models.IntegerField(blank=True, null=True)),
                ('wifi', models.CharField(max_length=100)),
                ('wifi_price', models.IntegerField()),
                ('software1', models.CharField(blank=True, max_length=100, null=True)),
                ('software1_price', models.IntegerField(blank=True, null=True)),
                ('software2', models.CharField(blank=True, max_length=100, null=True)),
                ('software2_price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('monitor', 'Monitor'), ('AIOM', 'AIO Monitor'), ('cabinet', 'Cabinet'), ('processor', 'Processor'), ('ram', 'RAM'), ('hdd', 'HDD'), ('ssd', 'SSD'), ('gp', 'Graphics Card'), ('os', 'Operating System'), ('motherboard', 'Motherboard'), ('AIOMotherboard', 'AIO Motherboard'), ('dvd', 'DVD'), ('wifi', 'WiFi'), ('keyboard', 'Keyboard'), ('warranty', 'Warranty'), ('software1', 'Software 1'), ('software2', 'Software 2')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyser', 'Analyzer'), ('user', 'User')], default='user', max_length=20)),
            ],
        ),
    ]
