# Generated by Django 6.0.4 on 2026-05-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_no', models.CharField(max_length=100, unique=True)),
                ('dept_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('atc', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('analyzer_review', 'Analyzer Review'), ('admin_review', 'Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('final_submitted', 'Final Submitted')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=200)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='accounts.bid')),
            ],
        ),
        migrations.CreateModel(
            name='BidPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='accounts.bid')),
            ],
        ),
        migrations.CreateModel(
            name='BidSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=100)),
                ('hdd', models.CharField(max_length=100)),
                ('ssd', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('monitor', models.CharField(max_length=100)),
                ('keyboard', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='accounts.bid')),
            ],
        ),
    ]
