# Generated by Django 6.0.4 on 2026-05-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_desktopbid_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopbid',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desktop_bids', to='accounts.user'),
        ),
    ]
