# Generated by Django 6.0.4 on 2026-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bid_bidmodel_bidpricing_bidspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidspecification',
            name='cabinet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='cabinet_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='dvd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='dvd_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='epbg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='freightInstallation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='freightInstallation_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='gp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='hdd_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='hddreturnable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='hddreturnable_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='keyboard_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='monitor_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='motherboard',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='motherboard_descp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='motherboard_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='os_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='pro_descp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='processor_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='ram_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='software1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='ssd_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='warranty_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='wifi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bidspecification',
            name='wifi_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_no',
            field=models.CharField(max_length=100),
        ),
    ]
