# Generated by Django 6.0.4 on 2026-05-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_desktopbid_submitted_by_desktopbid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopbid',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='jadmin_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
