# Generated by Django 6.0.4 on 2026-05-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aioproduct_bidproduct_price_priceitem'),
        ('accounts', '0003_bidspecification_cabinet_and_more'),
    ]

    operations = [
    ]
