# Generated by Django 6.0.4 on 2026-05-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_desktopbid_admin_note_desktopbid_jadmin_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktopbid',
            old_name='jadmin_username',
            new_name='admin_username',
        ),
    ]
