# Generated by Django 6.0.4 on 2026-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260504_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_no', models.CharField(max_length=100)),
                ('deptName', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('atc', models.TextField(blank=True, null=True)),
                ('processor', models.CharField(max_length=255)),
                ('pro_descp', models.TextField(blank=True, null=True)),
                ('processor_price', models.FloatField(default=0)),
                ('ram', models.CharField(max_length=100)),
                ('ram_price', models.FloatField(default=0)),
                ('hdd', models.CharField(blank=True, max_length=100, null=True)),
                ('hdd_price', models.FloatField(default=0)),
                ('ssd', models.CharField(blank=True, max_length=100, null=True)),
                ('ssd_price', models.FloatField(default=0)),
                ('software1', models.TextField()),
                ('gp', models.TextField()),
                ('os', models.CharField(max_length=100)),
                ('os_price', models.FloatField(default=0)),
                ('dvd', models.CharField(blank=True, max_length=50, null=True)),
                ('dvd_price', models.FloatField(default=0)),
                ('wifi', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_price', models.FloatField(default=0)),
                ('monitor', models.CharField(max_length=100)),
                ('monitor_price', models.FloatField(default=0)),
                ('cabinet', models.CharField(max_length=50)),
                ('cabinet_price', models.FloatField(default=0)),
                ('keyboard', models.CharField(blank=True, max_length=100, null=True)),
                ('keyboard_price', models.FloatField(default=0)),
                ('warranty', models.CharField(max_length=50)),
                ('warranty_price', models.FloatField(default=0)),
                ('motherboard', models.CharField(max_length=255)),
                ('motherboard_descp', models.TextField(blank=True, null=True)),
                ('motherboard_price', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('epbg', models.FloatField(default=0)),
                ('freightInstallation', models.CharField(default='Yes', max_length=50)),
                ('freightInstallation_price', models.FloatField(default=1000)),
                ('hddreturnable', models.CharField(default='Yes', max_length=50)),
                ('hddreturnable_price', models.FloatField(default=0)),
                ('model_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BidSpecification',
        ),
    ]
