# Generated by Django 6.0.4 on 2026-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_desktopbid_delete_bidspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktopbid',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
