# Generated by Django 6.0.4 on 2026-05-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_jadmin_username_desktopbid_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopbid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='desktopbid',
            name='gp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desktopbid',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='desktopbid',
            name='software1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
