# Generated by Django 6.0.4 on 2026-05-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_desktopbid_model_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopbid',
            name='address',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='atc',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='bid_no',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='deptName',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='qty',
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bid'),
        ),
    ]
