# Generated by Django 6.0.4 on 2026-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_desktopbid_updated_at_alter_desktopbid_gp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopbid',
            name='upload_document',
            field=models.FileField(blank=True, null=True, upload_to='desktop_bid_documents/'),
        ),
    ]
