# Generated by Django 6.0.4 on 2026-05-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_catalogueproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueproduct',
            name='processor',
            field=models.TextField(),
        ),
    ]
