# Generated by Django 6.0.4 on 2026-05-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_catalogueproduct_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueproduct',
            name='extra_specs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='processor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
