# Generated by Django 6.0.4 on 2026-05-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_catalogueproduct_extra_specs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueproduct',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='extra_specs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='ram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='storage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
