# Generated by Django 6.0.4 on 2026-06-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_gemproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeMProduct',
        ),
    ]
