# Generated by Django 6.0.4 on 2026-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_gemproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopbid',
            name='atc_special_document',
            field=models.FileField(blank=True, null=True, upload_to='atc_special/'),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='general_cert',
            field=models.FileField(blank=True, null=True, upload_to='general/'),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='general_exp',
            field=models.FileField(blank=True, null=True, upload_to='general/'),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='general_oem',
            field=models.FileField(blank=True, null=True, upload_to='general/'),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='general_oemT',
            field=models.FileField(blank=True, null=True, upload_to='general/'),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='general_perf',
            field=models.FileField(blank=True, null=True, upload_to='general/'),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='general_turn',
            field=models.FileField(blank=True, null=True, upload_to='general/'),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='extra_specs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='ram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='storage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
