# Generated by Django 6.0.4 on 2026-06-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_desktopbid_atc_special_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopbid',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='software1',
        ),
    ]
