# Generated by Django 6.0.4 on 2026-06-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_desktopbid_gp_remove_desktopbid_software1'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopbid',
            name='gp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='software1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
