# Generated by Django 6.0.4 on 2026-06-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_desktopbid_gp_desktopbid_software1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogueproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='catalogueproduct',
            name='os',
        ),
        migrations.RemoveField(
            model_name='catalogueproduct',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='catalogueproduct',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='catalogueproduct',
            name='storage',
        ),
        migrations.AlterField(
            model_name='catalogueproduct',
            name='extra_specs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
