# Generated by Django 6.0.4 on 2026-06-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_catalogueproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogueproduct',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogueproduct',
            name='processor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogueproduct',
            name='ram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='catalogueproduct',
            name='storage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
