# Generated by Django 6.0.4 on 2026-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_catalogueproduct_description_catalogueproduct_os_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopbid',
            name='atc_special_document',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='general_cert',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='general_exp',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='general_oem',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='general_oemT',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='general_perf',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='general_turn',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='upload_document',
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='selected_general_doc_labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='selected_general_docs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
