# Generated by Django 6.0.4 on 2026-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_desktopbid_atc_special_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopbid',
            name='atc_special_document',
            field=models.FileField(blank=True, null=True, upload_to='atc_special/'),
        ),
    ]
