# Generated by Django 6.0.4 on 2026-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_desktopbid_atc_special_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='gp_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='motherboard_descp_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='pro_descp_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='software1_price',
            field=models.FloatField(default=0),
        ),
    ]
