# Generated by Django 6.0.4 on 2026-06-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_delete_product_desktopbid_gp_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopbid',
            name='optional_port1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='optional_port2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='optional_port3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='desktopbid',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
