# Generated by Django 6.0.4 on 2026-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_desktopbid_optional_port1_desktopbid_optional_port2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopbid',
            name='optional_port1',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='optional_port2',
        ),
        migrations.RemoveField(
            model_name='desktopbid',
            name='optional_port3',
        ),
        migrations.AddField(
            model_name='desktopbid',
            name='optional_ports',
            field=models.TextField(blank=True, null=True),
        ),
    ]
