# Generated by Django 6.0.4 on 2026-06-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_workstationconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkstationConfig',
            new_name='WorkstationBid',
        ),
    ]
