# Generated by Django 6.0.4 on 2026-07-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_workstationconfig_workstationbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueproduct',
            name='model_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='desktopbid',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workstationbid',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
