# Generated by Django 6.0.4 on 2026-07-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_catalogueproduct_model_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueproduct',
            name='model_no',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workstationbid',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
