# Generated by Django 6.0.7 on 2026-07-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_catalogueproduct_model_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_no', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=1)),
                ('address', models.TextField()),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('atc', models.TextField(blank=True, null=True)),
                ('atc_special_document', models.FileField(blank=True, null=True, upload_to='atc_special_printer/')),
                ('selected_general_docs', models.JSONField(blank=True, default=list)),
                ('selected_general_doc_labels', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('printing_technology', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_printing', models.CharField(blank=True, max_length=50, null=True)),
                ('fax_availability', models.CharField(default='No', max_length=20)),
                ('mono_print_speed_ppm', models.CharField(blank=True, help_text='Mono ISO/IEC 24734 PPM (Laser/LED MFPs)', max_length=100, null=True)),
                ('mono_print_speed_ipm', models.CharField(blank=True, help_text='Mono ISO/IEC 24734 IPM (Inkjet MFPs)', max_length=100, null=True)),
                ('colour_print_speed_ppm', models.CharField(blank=True, help_text='Colour ISO/IEC 24734 PPM (Laser/LED MFPs)', max_length=100, null=True)),
                ('colour_print_speed_ipm', models.CharField(blank=True, help_text='Colour ISO/IEC 24734 IPM (Inkjet MFPs)', max_length=100, null=True)),
                ('auto_duplexing', models.CharField(default='Yes', max_length=20)),
                ('max_scan_area', models.CharField(blank=True, max_length=100, null=True)),
                ('scan_to_functions', models.CharField(blank=True, max_length=255, null=True)),
                ('document_feeder_type', models.CharField(blank=True, max_length=100, null=True)),
                ('feeder_capacity', models.CharField(blank=True, help_text='Number of Sheets', max_length=100, null=True)),
                ('main_paper_tray_count', models.CharField(blank=True, max_length=50, null=True)),
                ('total_paper_tray_capacity', models.CharField(blank=True, help_text='Combined capacity at 75 GSM', max_length=100, null=True)),
                ('bypass_tray_capacity', models.CharField(blank=True, help_text='Bypass tray capacity at 75 GSM', max_length=100, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=255, null=True)),
                ('duty_cycle', models.CharField(blank=True, help_text='Number of Prints/Month', max_length=100, null=True)),
                ('onsite_warranty', models.CharField(blank=True, help_text='On Site Warranty (in Years)', max_length=50, null=True)),
                ('extended_warranty', models.CharField(blank=True, help_text='Extended Warranty (in Years)', max_length=50, null=True)),
                ('software1', models.TextField(blank=True, null=True)),
                ('optional_ports', models.TextField(blank=True, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('epbg', models.FloatField(default=0)),
                ('freightInstallation', models.CharField(default='Yes', max_length=50)),
                ('add_amount', models.FloatField(default=0, help_text='Margin/Profit added')),
                ('final_amount', models.FloatField(default=0)),
                ('special_terms', models.TextField(blank=True, null=True)),
                ('bid_status', models.CharField(blank=True, help_text='Active, Won, Lost, Expired', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('analyser_note', models.TextField(blank=True, null=True)),
                ('analyser_username', models.CharField(blank=True, max_length=100, null=True)),
                ('review_status', models.CharField(default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('admin_username', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_bids', to='accounts.user')),
            ],
        ),
    ]
