# Generated by Django 6.0.7 on 2026-08-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_componentratehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemuploadjob',
            name='printer_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gem_upload_jobs', to='accounts.printerbid'),
        ),
        migrations.AddField(
            model_name='gemuploadjob',
            name='product_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('printer', 'Printer'), ('workstation', 'Workstation')], default='desktop', max_length=20),
        ),
        migrations.AddField(
            model_name='gemuploadjob',
            name='workstation_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gem_upload_jobs', to='accounts.workstationbid'),
        ),
        migrations.AddField(
            model_name='printerbid',
            name='gem_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printerbid',
            name='gem_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printerbid',
            name='gem_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printerbid',
            name='gem_product_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='printerbid',
            name='gem_status',
            field=models.CharField(default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='printerbid',
            name='gem_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workstationbid',
            name='gem_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workstationbid',
            name='gem_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workstationbid',
            name='gem_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workstationbid',
            name='gem_product_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='workstationbid',
            name='gem_status',
            field=models.CharField(default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='workstationbid',
            name='gem_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gemuploadjob',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gem_upload_jobs', to='accounts.desktopbid'),
        ),
    ]
