# Generated by Django 6.0.7 on 2026-08-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_gemuploadjob_printer_bid_gemuploadjob_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopbid',
            name='installation_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
