# Generated by Django 6.0.7 on 2026-08-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_desktopbid_installation_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopbid',
            name='installation_pincode',
        ),
    ]
